# Change these first
owner: phoneic
repo: status

# Monitoring sites
sites:
  - name: Productive.ai
    url: https://productive.ai

# Schedule for checks (every 5 minutes)
schedule: "*/5 * * * *"

status-website:
  cname: status.productive.ai
  baseUrl: /status
  name: Productive.ai Status
  logoUrl: /assets/logo.png
  introMessage: >
    Welcome to the Productive.ai status page. This page shows the current operational status of our services.
